# prepare.yml の実行対象のホストをここに書く。
# 新しいホストを準備するときはまずここに書いてから prepare.yml を実行する。
preparing_servers:
  hosts:
    ub1910x64prepared:
      running_ssh_host: 10.21.100.17
      prepare_temp_ssh_host: 10.21.100.17
      fqdn_hostname: ub1910x64prepared.sec.softether.co.jp


# prepare.yml が完了したら、ここに移動する。
running_servers:
