# prepare.yml の実行対象のホストをここに書く。
# 新しいホストを準備するときはまずここに書いてから prepare.yml を実行する。
preparing_servers:
  

# prepare.yml が完了したら、ここに移動する。
running_servers:
  hosts:
    ub2004pi4prepared:
      running_ssh_host: 10.21.100.37
      prepare_temp_ssh_host: 10.21.100.37
      fqdn_hostname: ub2004pi4prepared.sec.softether.co.jp
