# prepare.yml の実行対象のホストをここに書く。
# 新しいホストを準備するときはまずここに書いてから prepare.yml を実行する。
preparing_servers:


# prepare.yml が完了したら、ここに移動する。
running_servers:
  hosts:
    pi4ub1910prepared:
      running_ssh_host: 10.21.100.8
      prepare_temp_ssh_host: 10.21.100.8
      fqdn_hostname: pi4ub1910prepared.sec.softether.co.jp

